Lightning_FetchTable/objects/Job_Application__c.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>No_of_Selected__c</fullName>
        <label>No of Selected</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_of_applied__c</fullName>
        <label>No of applied</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Position_name__c</fullName>
        <label>Position name</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Job Application</label>
    <nameField>
        <label>Job Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Lightning_FetchTable/classes/testaura.cls
public class testaura {
  @AuraEnabled 
  public static AggregateResult[] getlocation() {
    return [select Location__c from job_application__c group by location__c]; 
  }
    @AuraEnabled 
  public static AggregateResult[] getposition() {
    return [select Position_name__c from job_application__c group by Position_name__c]; 
  }
      @AuraEnabled 
  public static list<Job_application__c> getdetails(string myselect1,string myselect2) {
     
      return [select Location__c,Position_name__c,No_of_applied__c,No_of_Selected__c,Year__c
            from job_application__c where
            Location__c = :myselect1 and Position_name__c = :myselect2 ]; 
  }
}